FROM ubuntu:latest
LABEL authors="User"

ENTRYPOINT ["top", "-b"]

FROM azul-zulu:25 AS builder
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM azul-zulu:25
WORKDIR /app
COPY --from=builder /app/target/*-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]